export const products = [
  {
    id: "nova-x1",
    sku: "VK-NX1-128-BLK",
    name: "Nova X1 5G",
    shortName: "Nova X1",
    category: "Phones",
    seller: "ValueKart Electronics",
    sellerShort: "ValueKart",
    price: 8997,
    mrp: 10999,
    upfront: 2999,
    installment: 2999,
    image: "phone",
    cashback: 250,
    delivery: "Tue, 28 Jul",
    returnPolicy: "7-day replacement",
    rating: 4.4,
    reviews: "1.8k",
    stock: 128,
    status: "PayLater eligible",
    statusTone: "positive",
    impressions: "42.6k",
    conversion: 7.8,
    returnRate: 2.4,
    contribution: 153,
  },
  {
    id: "blend-mini",
    sku: "NH-BM3-750-WHT",
    name: "BlendMini Mixer Grinder",
    shortName: "BlendMini",
    category: "Home",
    seller: "Nimble Home",
    sellerShort: "Nimble Home",
    price: 5997,
    mrp: 7499,
    upfront: 1999,
    installment: 1999,
    image: "mixer",
    cashback: 180,
    delivery: "Wed, 29 Jul",
    returnPolicy: "7-day replacement",
    rating: 4.5,
    reviews: "986",
    stock: 64,
    status: "PayLater eligible",
    statusTone: "positive",
    impressions: "31.9k",
    conversion: 8.6,
    returnRate: 1.8,
    contribution: 102,
  },
  {
    id: "pulse-buds",
    sku: "VK-PB2-BLK",
    name: "Pulse Buds 2",
    shortName: "Pulse Buds",
    category: "Audio",
    seller: "ValueKart Electronics",
    sellerShort: "ValueKart",
    price: 2499,
    mrp: 3499,
    upfront: 833,
    installment: 833,
    image: "earbuds",
    cashback: 99,
    delivery: "Tue, 28 Jul",
    returnPolicy: "7-day replacement",
    rating: 4.3,
    reviews: "2.4k",
    stock: 219,
    status: "PayLater eligible",
    statusTone: "positive",
    impressions: "58.2k",
    conversion: 10.1,
    returnRate: 3.1,
    contribution: 51,
  },
  {
    id: "focus-lamp",
    sku: "NH-FL1-MNT",
    name: "Focus Study Lamp",
    shortName: "Focus Lamp",
    category: "Work & Study",
    seller: "Nimble Home",
    sellerShort: "Nimble Home",
    price: 1797,
    mrp: 2299,
    upfront: 599,
    installment: 599,
    image: "lamp",
    cashback: 60,
    delivery: "Thu, 30 Jul",
    returnPolicy: "10-day return",
    rating: 4.6,
    reviews: "746",
    stock: 17,
    status: "Needs review",
    statusTone: "warning",
    impressions: "18.4k",
    conversion: 6.9,
    returnRate: 1.2,
    contribution: 31,
  },
];

export const categories = [
  { name: "For you", icon: "Sparkles" },
  { name: "Phones", icon: "Smartphone" },
  { name: "Home", icon: "House" },
  { name: "Audio", icon: "Headphones" },
  { name: "Work & Study", icon: "LampDesk" },
];

export const sellerOrders = [
  {
    id: "SM-28491",
    time: "25 Jul, 2:42 PM",
    customer: "Asha M.",
    product: "Nova X1 5G",
    plan: "Pay in 3",
    amount: 8997,
    status: "Ready to ship",
    settlement: "₹8,862",
  },
  {
    id: "SM-28488",
    time: "25 Jul, 2:18 PM",
    customer: "Rafiq A.",
    product: "Pulse Buds 2",
    plan: "Pay in 3",
    amount: 2499,
    status: "Packed",
    settlement: "₹2,461",
  },
  {
    id: "SM-28477",
    time: "25 Jul, 1:32 PM",
    customer: "Priya S.",
    product: "BlendMini Mixer Grinder",
    plan: "superCard EMI",
    amount: 5997,
    status: "Shipped",
    settlement: "₹5,907",
  },
  {
    id: "SM-28462",
    time: "25 Jul, 12:08 PM",
    customer: "Kabir R.",
    product: "Focus Study Lamp",
    plan: "Full UPI",
    amount: 1797,
    status: "Delivered",
    settlement: "₹1,770",
  },
];

export const formatINR = (value) =>
  new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(value);

export const paymentPlansFor = (product) => [
  {
    id: "pay3",
    label: "Pay in 3",
    eyebrow: "Recommended",
    dueToday: product.upfront,
    installment: product.installment,
    count: 2,
    total: product.price,
    fees: 0,
    lender: "DMI Finance",
  },
  {
    id: "card",
    label: "superCard EMI",
    eyebrow: "6 months",
    dueToday: 0,
    installment: Math.ceil(product.price / 6),
    count: 6,
    total: product.price,
    fees: 0,
    lender: "Utkarsh Small Finance Bank",
  },
  {
    id: "upi",
    label: "Full UPI",
    eyebrow: "No credit",
    dueToday: product.price,
    installment: 0,
    count: 0,
    total: product.price,
    fees: 0,
    lender: null,
  },
];
